name: frontend_lint
on: [pull_request]
jobs:
  frontend-lint:
    name: frontend-lint
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install -D
      - run: npm run fmt
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: yarn fmt

  frontend-openapi:
    name: frontend-openapi
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install -D
      - run: npm run openapi
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: yarn fmt